monitor.alsa.rules = [
  {
    matches = [ { device.name = "alsa_card.platform-c051000.sound-card" } ]
    actions = {
      update-props = {
        device.description = "Lenovo M10 Audio"
        api.alsa.use-ucm = true
        api.alsa.soft-mixer = true
      }
    }
  }
  {
    matches = [ { device.name = "alsa_card.comprC0" } ]
    actions = { update-props = { device.disabled = true } }
  }
]
