#!/usr/bin/env python3
"""Generate APKBUILDs from a checksum-pinned, published-source lock file."""
import hashlib,json,pathlib
ROOT=pathlib.Path(__file__).resolve().parents[1]
lock=json.loads((ROOT/'upstream.lock.json').read_text())
COMMON='meson samurai pkgconf gettext-dev gtk+3.0-dev gtkmm3-dev gtk-layer-shell-dev glm-dev wayland-dev wayland-protocols libxml2-dev libinput-dev libevdev-dev eudev-dev libdbusmenu-gtk3-dev menu-cache-dev'
NAMES={'wf-panel-pi':'rpd-panel','pplug-clock':'rpd-clock','wfplug-squeek':'rpd-keyboard-button','wfplug-wlist':'rpd-window-list','wfplug-imenu':'rpd-menu','pcmanfm-pi':'rpd-file-manager','pixtrix-theme':'rpd-theme','pixtrix-icons':'rpd-icons','rpd-metas':'rpd-menu-data'}
for name,m in lock.items():
 pkg=NAMES[name];p=ROOT/'ports'/pkg;p.mkdir(parents=True,exist_ok=True)
 asset=name in ['pixtrix-theme','pixtrix-icons','rpd-metas']
 license='MIT' if name=='wf-panel-pi' else 'GPL-2.0-or-later' if asset or name=='pcmanfm-pi' else 'BSD-3-Clause'
 depends='rpd-panel' if name.startswith('wfplug-') or name=='pplug-clock' else ''
 if name=='pixtrix-icons':depends='adwaita-icon-theme'
 # The portable session uses GTK3; Raspberry's GTK2 pixflat engine is omitted.
 extra='\nsubpackages="$pkgname-dev"' if name=='wf-panel-pi' else ''
 if name=='pcmanfm-pi':
  depends='!pcmanfm'
  extra+='\nsubpackages="$pkgname-doc"'
 text=f'''# Generated by scripts/generate.py. Local adaptations live in patches/.
pkgname={pkg}
pkgver={m['version']}
pkgrel={m['pkgrel']}
pkgdesc="Portable Raspberry Pi Desktop: {name}"
url="https://github.com/frenchfaso/rpd-apk"
arch="{'noarch' if asset else 'aarch64'}"
license="{license}"
depends="{depends}"
makedepends="{'' if asset else COMMON + (' rpd-panel-dev' if depends=='rpd-panel' else '')}"
options="!check"
# Upstream has no applicable test suite; repository smoke tests run separately.
source="{m['url']}"
builddir="$srcdir/{m['directory']}"{extra}
'''
 patches=sorted((p/'patches').glob('*.patch')) if (p/'patches').exists() else []
 if patches:text+='source="$source '+' '.join('patches/'+x.name for x in patches)+'"\n'
 if not asset:
  text+='''
build() {
    abuild-meson -Db_lto=false . output
    meson compile -C output
}
'''
 body='DESTDIR="$pkgdir" meson install --no-rebuild -C output' if not asset else {
 'pixtrix-theme':'mkdir -p "$pkgdir/usr/share"\n    cp -a usr/share/themes "$pkgdir/usr/share/"\n    rm -rf "$pkgdir/usr/share/themes/PiXtrix/gtk-2.0"',
 'pixtrix-icons':'mkdir -p "$pkgdir/usr/share/icons"\n    cp -a PiXtrix "$pkgdir/usr/share/icons/"',
 'rpd-metas':'mkdir -p "$pkgdir/etc/xdg/rpd/menus" "$pkgdir/usr/share"\n    cp common/etc/xdg/menus/rpd-applications.menu "$pkgdir/etc/xdg/rpd/menus/"\n    cp -a common/usr/share/desktop-directories "$pkgdir/usr/share/"',
 }[name]
 text+='\npackage() {\n    '+body+'\n    install -Dm644 debian/copyright "$pkgdir/usr/share/licenses/$pkgname/copyright"\n}\n'
 sums=[f"{m['sha512']}  {m['filename']}"]+[hashlib.sha512(x.read_bytes()).hexdigest()+'  '+x.name for x in patches]
 # abuild strips directory components when fetching local sources.
 text+='\nsha512sums="\n'+'\n'.join(sums)+'\n"\n'
 (p/'APKBUILD').write_text(text)
